#' Core deconstruction samples
#'
#' These tibbles capture the reciprocal square-root exploration datasets
#' generated by `run_deconstruction_pipeline()` in
#' `data-raw/pipelines/deconstruction.R`. Each object represents a different
#' sampling strategy used throughout the package visuals.
#'
#' @format Tibbles with the following columns:
#' \describe{
#'   \item{input}{Sampled floating-point inputs in \eqn{[0.5, 2)}.}
#'   \item{reference}{True reciprocal square-root for each input.}
#'   \item{initial}{Initial fast-inverse square-root estimate.}
#'   \item{after_one}{Value after a single Newton-Raphson refinement.}
#'   \item{final}{Final estimate returned by `frsrr::frsr_sample()`.}
#'   \item{iters}{Factor describing the number of iterations until convergence.}
#'   \item{magic}{Integer interpretation of the chosen magic constant.}
#'   \item{input_rank}{Quantile bin for the sampled input value.}
#'   \item{magic_rank}{Quantile bin for the selected magic constant.}
#'   \item{initial_rank}{Quantile bin for the initial approximation error.}
#'   \item{after_rank}{Quantile bin for the post-iteration error.}
#'   \item{iter_rank}{Binned iteration counts for plotting facets.}
#' }
#' @source `data-raw/pipelines/deconstruction.R`
"deconstructed"

#' Wider sweep deconstruction samples
#'
#' @rdname deconstructed
#' @source `data-raw/pipelines/deconstruction.R`
"widened"

#' Zoomed-in deconstruction samples
#'
#' @rdname deconstructed
#' @source `data-raw/pipelines/deconstruction.R`
"narrowed"
