# ---- Plot module: Historical comparisons -----------------------------------
# Visual layers for comparing historical approximations. Pair datasets from
# data-raw pipelines (see data-raw/pipelines/deconstruction.R for the
# approximated samples) with the wranglers in R/transform-history.R before
# plotting.

#' Historical approximation visualization builders.
#' 
#' Render comparisons across classical fast inverse square root
#' implementations using the outputs of \code{run_deconstruction_pipeline()}
#' and helper transforms such as [prep_example_samples()].
#'
#' @param approximated Tibble generated by [prep_example_samples()].
#' @param df Tibble from [prep_example_samples()].
#' @param approx Which approximation(s) to highlight in [nrplot()].
#' @return A [ggplot2::ggplot] object.
#' @name history_plots
#' @seealso \code{run_deconstruction_pipeline()} for regenerating the historical
#'   comparison datasets and [prep_example_samples()] for the transformation
#'   helper mentioned throughout this module.
NULL

#' @rdname history_plots
#' @export
plot_example_comparison <- function(approximated = prep_example_samples()) {
  ggplot2::ggplot(
    approximated,
    ggplot2::aes(
      x = input,
      y = (after_one - reference) / reference,
      color = method,
      linetype = method
    )
  ) +
    ggplot2::geom_line(linewidth = 1.25) +
    ggplot2::ylab("Relative Error") +
    ggplot2::xlab("Input") +
    ggplot2::labs(
      color = "Algorithm",
      linetype = "Algorithm",
      title = "Performance of four Fast Inverse Square Root algorithms"
    ) +
    ggplot2::scale_color_manual(
      values = c(
        "Blinn" = "blue",
        "QuakeIII" = "green",
        "Moroz" = "red",
        "Kahan" = "orange"
      ),
      labels = .blinncomp_labels
    ) +
    ggplot2::scale_linetype_manual(
      values = c(
        "Blinn" = "dashed",
        "QuakeIII" = "solid",
        "Moroz" = "solid",
        "Kahan" = "solid"
      ),
      labels = .blinncomp_labels
    ) +
    ggplot2::guides(color = ggplot2::guide_legend(override.aes = list(linewidth = 1.5))) +
    ggplot2::theme(
      legend.key.size = grid::unit(1.5, "cm"),
      legend.text = ggplot2::element_text(margin = ggplot2::margin(l = 10, unit = "pt"))
    ) +
    ggplot2::scale_x_continuous(
      trans = "log2",
      breaks = scales::trans_breaks("log2", function(x) 2^x, n = 4),
      labels = function(x) round(x, 4),
      limits = c(0.25, 1)
    )
}

#' @rdname history_plots
#' @export
plot_iteration_histogram <- function(approximated = prep_example_samples()) {
  ggplot2::ggplot(approximated) +
    ggplot2::geom_bar(ggplot2::aes(x = iters, fill = method), position = "dodge") +
    ggplot2::labs(
      title = "All four approximations converge to a tight tolerance in two iterations",
      y = "Count of samples",
      x = "Iterations",
      fill = "Approximation\nmethod"
    )
}

#' @rdname history_plots
#' @export
nrplot <- function(df = prep_example_samples(), approx = "QuakeIII") {
  target_xs <- seq(0.25, 2, by = 0.125)
  temp <- df |>
    dplyr::filter(method %in% approx)
  segment_data <- temp |>
    dplyr::mutate(closest_target = target_xs[sapply(input, function(x)
      which.min(abs(target_xs - x)))]) |>
    dplyr::group_by(closest_target) |>
    dplyr::slice_min(abs(input - closest_target), n = 1) |>
    dplyr::ungroup()
  temp |>
    dplyr::mutate(
      relErrGuess = (initial - reference) / reference,
      relErrNR = (after_one - reference) / reference
    ) |>
    ggplot2::ggplot(ggplot2::aes(x = input)) +
    ggplot2::geom_ribbon(ggplot2::aes(ymin = pmin(relErrGuess, relErrNR),
                    ymax = pmax(relErrGuess, relErrNR),
                    fill = method),
                alpha = 0.3) +
    ggplot2::geom_line(ggplot2::aes(y = relErrGuess,
                  linetype = "Initial guess"),
              linewidth = 1.1) +
    ggplot2::geom_line(ggplot2::aes(y = relErrNR,
                  linetype = "After one iteration")) +
    ggplot2::scale_linetype_manual(name = "Newton-Raphson",
                          breaks = c("Initial guess", "After one iteration"),
                          values = c("Initial guess" = "solid",
                                     "After one iteration" = "dotted")) +
    ggplot2::guides(fill = "none") +
    ggplot2::geom_segment(data = segment_data,
                 ggplot2::aes(x = input,
                     xend = input,
                     y = (initial - reference) / reference,
                     yend = (after_one - reference) / reference),
                 linewidth = 0.5,
                 arrow = grid::arrow(length = grid::unit(0.2, "cm"), type = "closed"),
                 show.legend = FALSE) +
    ggplot2::labs(
      y = "Relative error",
      title = "One iteration of Newton-Raphson markedly reduces error",
      x = "Input"
    )
}
